### ISSUE TITLE
Incorrect IpAddress namespace in address/codecs.cljc

### ISSUE THREAD

**Issue by ekimber** [greglook/clj-multiformats#3]
On line 7 of codecs.clj the import 
`[goog.net.IpAddress :as ip-address]`
is incorrect and should refer to `goog.net.ipaddress.IpAddress` [API doc](https://google.github.io/closure-library/api/goog.net.ipaddress.IpAddress.html)
I guess I will fork and submit a PR but anyway I thought I'd leave this here in the meantime to flag it up

**Comment by greglook** [comment]
Thanks for the report, I [see that failing](https://app.circleci.com/pipelines/github/greglook/clj-multiformats/53/workflows/f1b66a3b-03dc-4735-9c7e-96e41195ee50/jobs/120) now that I've gotten cljs tests actually running in CI. :sweat_smile: I'll fix it in the cleanup branch I'm working on.
