### ISSUE TITLE
bb compatibility

### ISSUE THREAD

**Issue by borkdude** [greglook/clj-multiformats#5]
Unfortunately this commit broke bb compatibility:

https://github.com/greglook/clj-multiformats/commit/2131ffa0361bb67a9fa2317ea250cf6fd29c4c15#r102553489

The `:bb` reader conditional must go before the :`clj` one, else bb will take the :clj reader conditional.
Also I forgot to add the `test-bb` step at the bottom of the CircleCI runner, my bad.

**Comment by greglook** [comment]
> The :bb reader conditional must go before the :clj one, else bb will take the :clj reader conditional.

Ah, TIL.
